# Generated by Django 5.1.6 on 2025-02-23 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_event_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='status',
        ),
    ]
